name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3

    - name: Install lcov
      run: brew install lcov

    - name: Configure CMake
      run: cmake .

    - name: Build
      run: make

    - name: Test
      run: ctest

    - name: lcov
      run: |
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '*/_deps/*' --output-file coverage.info
        lcov --remove coverage.info '/Applications/*' --output-file coverage.info    
 
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: coverage.info
