name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -DENABLE_COVERAGE=On .

    - name: Build
      run: make

    - name: Test
      run: ctest
     
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        gcov: true
        gcov_include: main.c
        directory: CMakeFiles/raa.dir/src/ 
