name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-12
    
    name: Build
    steps:
    - uses: actions/checkout@v3
    - name: run-cmake
      uses: lukka/run-cmake@v10.0
